### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by duzechao** [panpf/sketch#103]
没有设置点击事件，点击view就堆栈溢出了
`java.lang.StackOverflowError: stack size 8MB
        at me.panpf.sketch.viewfun.OnClickListenerProxy.onClick(OnClickListenerProxy.java:37)
        at me.panpf.sketch.viewfun.OnClickListenerProxy.onClick(OnClickListenerProxy.java:46)
        at me.panpf.sketch.viewfun.OnClickListenerProxy.onClick(OnClickListenerProxy.java:46)
        at me.panpf.sketch.viewfun.OnClickListenerProxy.onClick(OnClickListenerProxy.java:46)
        at me.panpf.sketch.viewfun.OnClickListenerProxy.onClick(OnClickListenerProxy.java:46)
        at me.panpf.sketch.viewfun.OnClickListenerProxy.onClick(OnClickListenerProxy.java:46)
        at me.panpf.sketch.viewfun.OnClickListenerProxy.onClick(OnClickListenerProxy.java:46)
        at me.panpf.sketch.viewfun.OnClickListenerProxy.onClick(OnClickListenerProxy.java:46)
        at me.panpf.sketch.viewfun.OnClickListenerProxy.onClick(OnClickListenerProxy.java:46)
        at me.panpf.sketch.viewfun.OnClickListenerProxy.onClick(OnClickListenerProxy.java:46)
        at me.panpf.sketch.viewfun.OnClickListenerProxy.onClick(OnClickListenerProxy.java:46)
        at me.panpf.sketch.viewfun.OnClickListenerProxy.onClick(OnClickListenerProxy.java:46)
        at me.panpf.sketch.viewfun.OnClickListenerProxy.onClick(OnClickListenerProxy.java:46)
        at me.panpf.sketch.viewfun.OnClickListenerProxy.onClick(OnClickListenerProxy.java:46)`

**Comment by duzechao** [comment]
`java.lang.StackOverflowError: stack size 8MB
        at me.panpf.sketch.viewfun.ClickRetryFunction.onClick(ClickRetryFunction.java:81)
        at me.panpf.sketch.viewfun.OnClickListenerProxy.onClick(OnClickListenerProxy.java:37)
        at me.panpf.sketch.viewfun.OnClickListenerProxy.onClick(OnClickListenerProxy.java:46)
        at me.panpf.sketch.viewfun.OnClickListenerProxy.onClick(OnClickListenerProxy.java:46)
        at me.panpf.sketch.viewfun.OnClickListenerProxy.onClick(OnClickListenerProxy.java:46)
        at me.panpf.sketch.viewfun.OnClickListenerProxy.onClick(OnClickListenerProxy.java:46)
        at me.panpf.sketch.viewfun.OnClickListenerProxy.onClick(OnClickListenerProxy.java:46)
        at me.panpf.sketch.viewfun.OnClickListenerProxy.onClick(OnClickListenerProxy.java:46)
        at me.panpf.sketch.viewfun.OnClickListenerProxy.onClick(OnClickListenerProxy.java:46)
        at me.panpf.sketch.viewfun.OnClickListenerProxy.onClick(OnClickListenerProxy.java:46)
        at me.panpf.sketch.viewfun.OnClickListenerProxy.onClick(OnClickListenerProxy.java:46)
        at me.panpf.sketch.viewfun.OnClickListenerProxy.onClick(OnClickListenerProxy.java:46)
        at me.panpf.sketch.viewfun.OnClickListenerProxy.onClick(OnClickListenerProxy.java:46)`

**Comment by duzechao** [comment]
主要是这段代码有问题
`/**
     * 点击事件
     *
     * @param v View
     * @return true：已经消费了，不必往下传了
     */
    public boolean onClick(View v) {
        if (isClickable()) {
            if (redisplayListener == null) {
                redisplayListener = new RetryOnPauseDownloadRedisplayListener();
            }

            return view.redisplay(redisplayListener);
        }

        return false;
    }`

**Comment by panpf** [comment]
暂时没看出来哪里的问题，能描述清楚你都开了什么功能吗？或者把跟 SketchImageView 相关的所有代码贴出来
