### ISSUE TITLE
我在使用的时候遇到了这个 width and height must be > 0

### ISSUE THREAD

**Issue by GentleLi** [panpf/sketch#119]
java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1013)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:980)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:930)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:891)
        at me.panpf.sketch.cache.BitmapPoolUtils.setInBitmapFromPoolForRegionDecoder(BitmapPoolUtils.java:154)
        at me.panpf.sketch.zoom.block.DecodeHandler.decode(DecodeHandler.java:125)
        at me.panpf.sketch.zoom.block.DecodeHandler.handleMessage(DecodeHandler.java:72)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:192)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by panpf** [comment]
必现吗？如果是必现的话，列出你的环境，设备，系统？图片url？

**Comment by GentleLi** [comment]
不是必现，但是会遇到，貌似跟图片url关系不大，我在预览不同的图片时出现，下次遇到后，我会给你图片地址 
使用版本 me.panpf:sketch:2.6.2-b1  和 me.panpf:sketch-gif:2.6.2-b1   
机型Vivo X9s 系统 8.1.0

**Comment by GentleLi** [comment]
地址： https://cdn-public.knowyourself.cc/2019/08/01/58415410-4129-432f-9881-cb486631e4ba.jpg

**Comment by feimenggo** [comment]
我在线上环境，也一直遇到这个错误
```
java.lang.IllegalArgumentException: width and height must be > 0
    at android.graphics.Bitmap.createBitmap(Bitmap.java:877)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:856)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:823)
    at me.panpf.sketch.a.b.a(BitmapPoolUtils.java)
    at me.panpf.sketch.zoom.block.DecodeHandler.a(DecodeHandler.java)
    at me.panpf.sketch.zoom.block.DecodeHandler.handleMessage(DecodeHandler.java)
    at android.os.Handler.dispatchMessage(Handler.java:110)
    at android.os.Looper.loop(Looper.java:203)
    at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by feimenggo** [comment]
![图片](https://user-images.githubusercontent.com/12608693/62435490-f10da680-b76e-11e9-83b1-395a9b1cfe3c.png)

**Comment by panpf** [comment]
好的，我这几天抽空看一下

**Comment by revstar** [comment]
我也遇到了

**Comment by panpf** [comment]
最新版本 2.7.1-rc01 已经试着修复了此问题，大家可以更新试一下
