### ISSUE TITLE
release 中的示例 apk 在启动时崩溃

### ISSUE THREAD

**Issue by klxiaoniu** [panpf/sketch#190]
**Describe the bug**

下载安装 release 中的示例 apk，在启动时出现 crash

**Versions**

- sketch version*: v3.3.0-beta04 或 v3.3.0-beta03
- Kotlin version*: 尚未应用于业务中
- Compose version(s)*: /
- Running Devices (*) (Model, OS, CPU Architecture, JDK.):
    - Redmi K50 ; MIUI 14; arm64

**Sample code**

/

**Reproduction steps**

如上述

**Expected behavior**

/

**Screenshots**

/

**Additional context**

以下是 beta04 崩溃日志
[Device Brand]: Redmi
[Device Model]: 22041211AC
[Display]: TP1A.220624.014
[Android Version]: 13
[Android API Level]: 33
[System Locale]: zh_CN
[Process ID]: 17900
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: com.github.panpf.sketch3.sample
[Version Name]: 3.3.0-beta04
[Version Code]: 3304
[Target SDK]: 28
[Min SDK]: 16
[Error Type]: JVM
[Crash Time]: 2023-12-15T07:39:30.504
[Stack Trace]:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.panpf.sketch3.sample/com.github.panpf.sketch.sample.ui.MainActivity}: java.lang.IllegalArgumentException: 'class com.github.panpf.sketch.sample.ui.MainActivity' parent class of must have a generic parameter
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3802)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3948)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8136)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: java.lang.IllegalArgumentException: 'class com.github.panpf.sketch.sample.ui.MainActivity' parent class of must have a generic parameter
	at l8.b.L3(SourceFile:89)
	at h5.a.onCreate(SourceFile:64)
	at android.app.Activity.performCreate(Activity.java:8522)
	at android.app.Activity.performCreate(Activity.java:8486)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3783)
	... 12 more

**Comment by panpf** [comment]
以下掉 sample apk，新版本修复后再上传，暂时辛苦编译源码体验吧

**Comment by klxiaoniu** [comment]
> 已下掉 sample apk，新版本修复后再上传，暂时辛苦编译源码体验吧

好的

**Comment by panpf** [comment]
3.3.0-beta05 版本已发布，已修复 sample app 启动时崩溃的问题
