### ISSUE TITLE
类型转换异常

### ISSUE THREAD

**Issue by FreeVic** [panpf/sketch#43]
Version release 2.4.1(2410)
09-01 18:23:28.234 7929-7929/com.eclite.activity W/Bundle: Key XG_V2_ACCESS_ID expected String but value was a java.lang.Integer.  The default value <null> was returned.
09-01 18:23:28.235 7929-7929/com.eclite.activity W/Bundle: Attempt to cast generated internal exception:
                                                           java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
                                                               at android.os.BaseBundle.getString(BaseBundle.java:995)
                                                               at me.xiaopan.sketch.util.SketchUtils.findInitializer(SketchUtils.java:1240)
                                                               at me.xiaopan.sketch.Sketch.with(Sketch.java:69)
                                                               at me.xiaopan.sketch.viewfun.large.TileDecodeCallbackHandler.<init>(TileDecodeCallbackHandler.java:51)
                                                               at me.xiaopan.sketch.viewfun.large.TileExecutor.<init>(TileExecutor.java:50)
                                                               at me.xiaopan.sketch.viewfun.large.LargeImageViewer.<init>(LargeImageViewer.java:69)
                                                               at me.xiaopan.sketch.viewfun.LargeImageFunction.<init>(LargeImageFunction.java:49)
                                                               at me.xiaopan.sketch.viewfun.FunctionPropertyView.setBlockDisplayLargeImageEnabled(FunctionPropertyView.java:363)
                                                               at com.eclite.activity.ImageDetailActivityNew$ImagePagerAdapter.instantiateItem(ImageDetailActivityNew.java:419)
                                                               at com.eclite.activity.ImageDetailActivityNew$ImagePagerAdapter.instantiateItem(ImageDetailActivityNew.java:392)
                                                               at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1006)
                                                               at android.support.v4.view.ViewPager.populate(ViewPager.java:1154)
                                                               at android.support.v4.view.ViewPager.populate(ViewPager.java:1088)
                                                               at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1614)
                                                               at android.view.View.measure(View.java:19867)
                                                               at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                               at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                               at android.view.View.measure(View.java:19867)
                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                               at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                               at android.view.View.measure(View.java:19867)
                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                               at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                               at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                               at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                               at android.view.View.measure(View.java:19867)
                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                               at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                               at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
                                                               at android.view.View.measure(View.java:19867)
                                                               at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2336)
                                                               at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1427)
                                                               at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1680)
                                                               at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1315)
                                                               at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6420)
                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:688)
                                                               at android.view.Choreographer.doFrame(Choreographer.java:623)
                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
                                                               at android.os.Handler.handleCallback(Handler.java:751)
                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                               at android.os.Looper.loop(Looper.java:154)
                                                               at android.app.ActivityThread.main(ActivityThread.java:6165)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)

**Comment by panpf** [comment]
下个版本会修复
