### ISSUE TITLE
部分网络图片无法加载

### ISSUE THREAD

**Issue by onlymash** [panpf/sketch#75]
这是设置 useragent
```
val Context.userAgent: String
    get() = android.webkit.WebSettings.getDefaultUserAgent(this)
val hurlStack = HurlStack()
 hurlStack.userAgent = context.userAgent
Sketch.with(context).configuration.httpStack = hurlStack
```

然后无法加载， 同样的资源， glide是可以加载的

```
06-15 16:32:28.989 31186-31186/im.mash.moebooru.debug I/Sketch: Version release 2.6.1(2610) -> Configuration: 
    uriModelManager：UriModelManager
    optionsFilterManager：OptionsFilterManager
    diskCache：LruDiskCache(maxSize=105兆字节,appVersionCode=2,cacheDir=/storage/emulated/0/Android/data/im.mash.moebooru.debug/cache/sketch)
    bitmapPool：LruBitmapPool(maxSize=23.20兆字节,strategy=SizeConfigStrategy,allowedConfigs=[null, RGBA_F16, ALPHA_8, ARGB_8888, ARGB_4444, RGB_565, HARDWARE])
    memoryCache：LruMemoryCache(maxSize=23.20兆字节)
    processedImageCache：ProcessedImageCache
    httpStack：HurlStack(maxRetryCount=0,connectTimeout=7000,readTimeout=7000,userAgent=null)
    decoder：ImageDecoder
    downloader：ImageDownloader
    orientationCorrector：ImageOrientationCorrector
    defaultDisplayer：DefaultImageDisplayer
    resizeProcessor：ResizeImageProcessor
    resizeCalculator：ResizeCalculator
    sizeCalculator：ImageSizeCalculator
    freeRideManager：FreeRideManager
    executor：RequestExecutor(running)
    helperFactory：HelperFactory
    requestFactory：RequestFactory
    errorTracker：ErrorTracker
    pauseDownload：false
    pauseLoad：false
    lowQualityImage：false
    inPreferQualityOverSpeed：false
    mobileDataPauseDownload：false
06-15 16:32:31.437 31186-31338/im.mash.moebooru.debug W/System.err: java.io.FileNotFoundException: https://files.yande.re/sample/8c03bff9948a6c59310a2d3491d9fd43/yande.re%20459652%20sample%20animal_ears%20bikini%20dduck_kong%20fate_grand_order%20see_through%20swimsuits%20tail%20tamamo_no_mae%20wet%20wet_clothes.jpg
06-15 16:32:31.438 31186-31338/im.mash.moebooru.debug W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
06-15 16:32:31.439 31186-31338/im.mash.moebooru.debug W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
06-15 16:32:31.440 31186-31338/im.mash.moebooru.debug W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(Unknown Source:0)
        at me.panpf.sketch.http.HurlStack$HurlResponse.getContent(HurlStack.java:221)
        at me.panpf.sketch.http.HurlStack$HurlResponse.releaseConnection(HurlStack.java:227)
        at me.panpf.sketch.http.ImageDownloader.doDownload(ImageDownloader.java:190)
06-15 16:32:31.441 31186-31338/im.mash.moebooru.debug W/System.err:     at me.panpf.sketch.http.ImageDownloader.loopRetryDownload(ImageDownloader.java:111)
        at me.panpf.sketch.http.ImageDownloader.download(ImageDownloader.java:84)
        at me.panpf.sketch.request.DownloadRequest.runDownload(DownloadRequest.java:150)
        at me.panpf.sketch.request.FreeRideDownloadRequest.runDownload(FreeRideDownloadRequest.java:74)
        at me.panpf.sketch.request.AsyncRequest.executeDownload(AsyncRequest.java:80)
06-15 16:32:31.442 31186-31338/im.mash.moebooru.debug W/System.err:     at me.panpf.sketch.request.AsyncRequest.run(AsyncRequest.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
06-15 16:32:31.443 31186-31340/im.mash.moebooru.debug W/System.err: java.io.FileNotFoundException: https://files.yande.re/sample/44f3da62e0668faa77a4c36fb5afd1d4/yande.re%20459653%20sample%20animal_ears%20ehrrr%20garter%20heels%20inubashiri_momiji%20signed%20sword%20tail%20touhou.jpg
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
06-15 16:32:31.444 31186-31340/im.mash.moebooru.debug W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(Unknown Source:0)
06-15 16:32:31.445 31186-31340/im.mash.moebooru.debug W/System.err:     at me.panpf.sketch.http.HurlStack$HurlResponse.getContent(HurlStack.java:221)
        at me.panpf.sketch.http.HurlStack$HurlResponse.releaseConnection(HurlStack.java:227)
        at me.panpf.sketch.http.ImageDownloader.doDownload(ImageDownloader.java:190)
        at me.panpf.sketch.http.ImageDownloader.loopRetryDownload(ImageDownloader.java:111)
        at me.panpf.sketch.http.ImageDownloader.download(ImageDownloader.java:84)
06-15 16:32:31.446 31186-31340/im.mash.moebooru.debug W/System.err:     at me.panpf.sketch.request.DownloadRequest.runDownload(DownloadRequest.java:150)
        at me.panpf.sketch.request.FreeRideDownloadRequest.runDownload(FreeRideDownloadRequest.java:74)
        at me.panpf.sketch.request.AsyncRequest.executeDownload(AsyncRequest.java:80)
        at me.panpf.sketch.request.AsyncRequest.run(AsyncRequest.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
06-15 16:32:31.449 31186-31338/im.mash.moebooru.debug E/Sketch: ImageDownloader. Response code exception. responseHeaders: [{null:HTTP/1.1 403 Forbidden}, {Connection:keep-alive}, {Content-Type:text/html}, {Date:Fri, 15 Jun 2018 08:32:31 GMT}, {Server:nginx/1.14.0}, {Strict-Transport-Security:max-age=31536000}, {Transfer-Encoding:chunked}, {X-Android-Received-Millis:1529051551434}, {X-Android-Response-Source:NETWORK 403}, {X-Android-Selected-Protocol:http/1.1}, {X-Android-Sent-Millis:1529051551065}]. DownloadThread1. https://files.yande.re/sample/8c03bff9948a6c59310a2d3491d9fd43/yande.re%20459652%20sample%20animal_ears%20bikini%20dduck_kong%20fate_grand_order%20see_through%20swimsuits%20tail%20tamamo_no_mae%20wet%20wet_clothes.jpg?options=MaxSize(1080x1790)
06-15 16:32:31.451 31186-31338/im.mash.moebooru.debug W/System.err: me.panpf.sketch.http.DownloadException: Response code exception. responseHeaders: [{null:HTTP/1.1 403 Forbidden}, {Connection:keep-alive}, {Content-Type:text/html}, {Date:Fri, 15 Jun 2018 08:32:31 GMT}, {Server:nginx/1.14.0}, {Strict-Transport-Security:max-age=31536000}, {Transfer-Encoding:chunked}, {X-Android-Received-Millis:1529051551434}, {X-Android-Response-Source:NETWORK 403}, {X-Android-Selected-Protocol:http/1.1}, {X-Android-Sent-Millis:1529051551065}]. DownloadThread1. https://files.yande.re/sample/8c03bff9948a6c59310a2d3491d9fd43/yande.re%20459652%20sample%20animal_ears%20bikini%20dduck_kong%20fate_grand_order%20see_through%20swimsuits%20tail%20tamamo_no_mae%20wet%20wet_clothes.jpg?options=MaxSize(1080x1790)
06-15 16:32:31.451 31186-31340/im.mash.moebooru.debug E/Sketch: ImageDownloader. Response code exception. responseHeaders: [{null:HTTP/1.1 403 Forbidden}, {Connection:keep-alive}, {Content-Type:text/html}, {Date:Fri, 15 Jun 2018 08:32:31 GMT}, {Server:nginx/1.14.0}, {Strict-Transport-Security:max-age=31536000}, {Transfer-Encoding:chunked}, {X-Android-Received-Millis:1529051551439}, {X-Android-Response-Source:NETWORK 403}, {X-Android-Selected-Protocol:http/1.1}, {X-Android-Sent-Millis:1529051551078}]. DownloadThread2. https://files.yande.re/sample/44f3da62e0668faa77a4c36fb5afd1d4/yande.re%20459653%20sample%20animal_ears%20ehrrr%20garter%20heels%20inubashiri_momiji%20signed%20sword%20tail%20touhou.jpg?options=MaxSize(1080x1790)
06-15 16:32:31.452 31186-31338/im.mash.moebooru.debug W/System.err:     at me.panpf.sketch.http.ImageDownloader.doDownload(ImageDownloader.java:213)
```

**Comment by onlymash** [comment]
日志里 userAgent=null  不知道为什么不生效

**Comment by panpf** [comment]
sketch 在 user-agent 方面没有做什么设置，都是默认的，你可以抓包看看 glide 的和 sketch 发出的请求头有什么区别

**Comment by panpf** [comment]
你贴出来的日志里面的 userAgent 是初始化的时候的值，肯定是空的，你后来改的会有另外的日志

**Comment by onlymash** [comment]
现在可以加载了 不过 viuewpager 翻不了几页就崩了。
很喜欢 bm-x/PhotoView 的多点拖动旋转图片，不知道能不能在 sketch 实现

```
06-15 16:55:36.115 4339-4461/im.mash.moebooru.debug W/System.err: me.panpf.sketch.http.DownloadException: Download exception, but canceled. DownloadThread1. https://files.yande.re/sample/5dc8c7e266132ad202ff7dbc9441aa22/yande.re%20459597%20sample%20breast_hold%20breasts%20cameltoe%20garter%20inue_shinsuke%20nipples%20pointy_ears%20sling_bikini%20swimsuits%20tagme.jpg?options=MaxSize(1080x1790)
06-15 16:55:36.116 4339-4461/im.mash.moebooru.debug W/System.err:     at me.panpf.sketch.http.ImageDownloader.loopRetryDownload(ImageDownloader.java:122)
        at me.panpf.sketch.http.ImageDownloader.download(ImageDownloader.java:84)
06-15 16:55:36.117 4339-4461/im.mash.moebooru.debug W/System.err:     at me.panpf.sketch.request.DownloadRequest.runDownload(DownloadRequest.java:150)
        at me.panpf.sketch.request.FreeRideDownloadRequest.runDownload(FreeRideDownloadRequest.java:74)
        at me.panpf.sketch.request.AsyncRequest.executeDownload(AsyncRequest.java:80)
        at me.panpf.sketch.request.AsyncRequest.run(AsyncRequest.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
06-15 16:55:36.118 4339-4461/im.mash.moebooru.debug W/System.err: Caused by: me.panpf.sketch.request.CanceledException
        at me.panpf.sketch.http.ImageDownloader.readData(ImageDownloader.java:355)
        at me.panpf.sketch.http.ImageDownloader.doDownload(ImageDownloader.java:268)
06-15 16:55:36.119 4339-4461/im.mash.moebooru.debug W/System.err:     at me.panpf.sketch.http.ImageDownloader.loopRetryDownload(ImageDownloader.java:111)
    	... 8 more
06-15 16:55:39.922 4339-4339/im.mash.moebooru.debug E/InputEventReceiver: Exception dispatching input event.
06-15 16:55:39.922 4339-4339/im.mash.moebooru.debug E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
06-15 16:55:39.926 4339-4339/im.mash.moebooru.debug E/MessageQueue-JNI: java.lang.IllegalArgumentException: pointerIndex out of range
        at android.view.MotionEvent.nativeGetAxisValue(Native Method)
        at android.view.MotionEvent.getY(MotionEvent.java:2216)
        at im.mash.moebooru.core.widget.VerticalViewPager.onInterceptTouchEvent(VerticalViewPager.java:1814)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2511)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:448)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1829)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3307)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:410)
        at android.view.View.dispatchPointerEvent(View.java:12015)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4795)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4609)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4293)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4174)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4350)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4174)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6661)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6635)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6596)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6764)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
06-15 16:55:39.926 4339-4339/im.mash.moebooru.debug D/AndroidRuntime: Shutting down VM
06-15 16:55:39.930 4339-4339/im.mash.moebooru.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: im.mash.moebooru.debug, PID: 4339
    java.lang.IllegalArgumentException: pointerIndex out of range
        at android.view.MotionEvent.nativeGetAxisValue(Native Method)
        at android.view.MotionEvent.getY(MotionEvent.java:2216)
        at im.mash.moebooru.core.widget.VerticalViewPager.onInterceptTouchEvent(VerticalViewPager.java:1814)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2511)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:448)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1829)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3307)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:410)
        at android.view.View.dispatchPointerEvent(View.java:12015)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4795)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4609)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4293)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4174)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4350)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4174)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6661)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6635)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6596)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6764)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by panpf** [comment]
崩溃的 这里有说明 https://github.com/panpf/sketch/blob/master/docs/wiki/zoom.md

**Comment by panpf** [comment]
我还没有体验过 bm-x/PhotoView 不清楚你说的多点缩放是什么效果，但是我大概看了下 bm-x/PhotoView 的介绍，他能支持 Glide、ImageLoader，那么你稍微花点儿工夫也能让它支持 Sketch

**Comment by onlymash** [comment]
@panpf 就是两个手指按住图片不放，手指旋转， 图片也跟着旋转。可以在不旋转设备的情况下旋转图片，快图浏览也有这个功能，你可以试试。

**Comment by panpf** [comment]
好的

**Comment by onlymash** [comment]
旋转效果 https://github.com/bm-x/PhotoView/blob/master/demo1.gif
